# NaturalGrowth Configuration

# Global settings
doPlaceDespawn: true
doPlaceCrops: true
do2x2Placement: true

# List of items that can be automatically planted
itemDespawnList:
  - ACACIA_SAPLING
  - BIRCH_SAPLING
  - CHERRY_SAPLING
  - DARK_OAK_SAPLING
  - OAK_SAPLING
  - SPRUCE_SAPLING
  - BAMBOO
  - BROWN_MUSHROOM
  - RED_MUSHROOM
  - CACTUS
  - ALLIUM
  - AZALEA_BUSH
  - AZURE_BLUET
  - BLUE_ORCHID
  - CORNFLOWER
  - CRIMSON_FUNGUS
  - CRIMSON_ROOTS
  - DANDELION
  - DEAD_BUSH
  - FERN
  - FLOWERING_AZALEA_BUSH
  - JUNGLE_SAPLING
  - LILY_OF_THE_VALLEY
  - MANGROVE_PROPAGULE
  - ORANGE_TULIP
  - OXEYE_DAISY
  - PINK_TULIP
  - PITCHER_PLANT
  - POPPY
  - RED_TULIP
  - TORCHFLOWER
  - WARPED_FUNGUS
  - WARPED_ROOTS
  - WHITE_TULIP
  - WITHER_ROSE

# List of crops that can be automatically planted (format: SEED:CROP)
cropDespawnList:
  - POTATO:POTATOES
  - WHEAT_SEEDS:WHEAT
  - BEETROOT_SEEDS:BEETROOTS
  - MELON_SEEDS:MELON_STEM
  - PUMPKIN_SEEDS:PUMPKIN_STEM
  - TORCHFLOWER_SEEDS:TORCHFLOWER_CROP
  - PITCHER_POD:PITCHER_CROP
  - CARROT:CARROTS

# List of saplings that can be placed in 2x2 pattern
item2x2List:
  - spruce
  - dark_oak
  - jungle

# Town-specific settings (will be populated as towns toggle the feature)
townSettings: {} 