name: NaturalGrowth
main: thephilosophicat.tv.twitch.NaturalGrowth.NaturalGrowthMain
version: 1.4
api-version: '1.21'
depend: [Towny]

commands:
   doplacedespawn:
      description: changes config to enable/disable placing despawned items
      usage: "/<command> [True | False]" 
      permission: plugin.Rules
   doplacecrops:
      description: changes config to enable/disable placing despawned seeds
      usage: "/<command> [True | False]"
      permission: plugin.Rules
   do2x2placement:
      description: changes config to enable/disable placing items in a 2x2 fashion
      usage: "/<command> [True | False]" 
      permission: plugin.Rules
   toggletowngrowth:
      description: Toggle natural growth for your town
      usage: "/<command> [True | False]"
      permission: naturalgrowth.town.toggle

permissions:
  plugin.Rules:
    description: allows players to change config settings
    default: op
  naturalgrowth.town.toggle:
    description: Allows toggling natural growth for their town
    default: false